app/controllers/blog.py
# -*- coding: UTF-8 -*-
from flask import render_template, Blueprint, redirect, url_for
from flask_login import login_required, current_user
from flask_principal import Permission, UserNeed, RoleNeed
from sqlalchemy import func

from app.models import db, User, Post, Tag, Comment, posts_tags
from datetime import datetime
from os import path
from uuid import uuid4
from app.forms import CommentForm, PostForm
from app.extensions import admin_permission, poster_permission, default_permission

blog_blueprint = Blueprint(
    'blog',
    __name__,
    # path.pardir ==> ..
    template_folder=path.join(path.pardir, 'templates', 'blog'),
    # Prefix of Route URL
    url_prefix='/blog')

def sidebar_data():
    """ Set the sidebar function. """

    recent = db.session.query(Post).order_by(Post.publish_date.desc()).limit(5).all()

    top_tags = db.session.query(
        Tag, func.count(posts_tags.c.post_id).label('total')
    ).join(
        posts_tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@login_required
def home(page=1):
    """View function for home page"""

    posts = Post.query.order_by(
        Post.publish_date.desc()
    ).paginate(page, 10)

    recent, top_tags = sidebar_data()

    return render_template('home.html',
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/post/<string:post_id>', methods=('GET', 'POST'))
@login_required
def post(post_id):
    """View function for post page"""

    # Form object: `Comment`
    form = CommentForm()
    # form.validate_on_submit() will be true and return the
    # data object to form instance from user enter,
    # when the HTTP request is POST
    if form.validate_on_submit():
        new_comment = Comment(id=str(uuid4()),
                              name=form.name.data)
        new_comment.text = form.text.data
        new_comment.date = datetime.now()
        new_comment.post_id = post_id
        db.session.add(new_comment)
        db.session.commit()

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('post.html',
                           post=post,
                           tags=tags,
                           comments=comments,
                           form=form,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/tag/<string:tag_name>')
@login_required
def tag(tag_name):
    """View function for tag page"""

    tag = db.session.query(Tag).filter_by(name=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('tag.html',
                           tag=tag,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/user/<string:username>')
@login_required
def user(username):
    """View function for user page"""
    user = db.session.query(User).filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('user.html',
                           user=user,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)

@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """View function for new_port."""
    form = PostForm()

    # Ensure the user logged in.
    # Flask-Login.current_user can be access current user.
    if not current_user:
        return redirect(url_for('main.login'))

    if form.validate_on_submit():
        new_post = Post(id=str(uuid4()), title=form.title.data)
        new_post.text = form.text.data
        new_post.publish_date = datetime.now()
        new_post.users = current_user

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.home'))

    return render_template('new_post.html',
                           form=form)


@blog_blueprint.route('/edit/<string:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def edit_post(id):
    """View function for edit_post."""

    post = Post.query.get_or_404(id)
    form = PostForm()

    # Ensure the user logged in.
    if not current_user:
        return redirect(url_for('main.login'))

    # Only the post onwer can be edit this post.
    if current_user != post.users:
        return redirect(url_for('blog.post', post_id=id))

    # 当 user 是 poster 或者 admin 时, 才能够编辑文章
    # Admin can be edit the post.
    permission = Permission(UserNeed(post.users.id))
    if permission.can() or admin_permission.can():

        # if current_user != post.users:
        #    abort(403)

        if form.validate_on_submit():
            post.title = form.title.data
            post.text = form.text.data
            post.publish_date = datetime.now()

            # Update the post
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.post', post_id=post.id))
    else:
        return redirect(url_for('blog.post', post_id=id))

    form.title.data = post.title
    form.text.data = post.text
    return render_template('edit_post.html', form=form, post=post)

app/templates/blog/edit_post.html
{% extends "base.html" %}

{% block title %}Edit Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Edit the Post</h1>
  <form method="POST" action="{{ url_for('blog.edit_post', id=post.id) }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control', value=post.title) }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

app/templates/blog/home.html
<!-- Replace the TITLE of template base.html -->
{% extends "base.html" %}
{% block title %}Leo's Blog{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
    <!-- The data object from view function: `home()` -->
    <div class="row">
        <div class="col-lg-9">
            <!-- Get Pagination object-->
            {% for post in posts.items %}
                <div class="row">
                    <div class="col-lg-12">
                        <h1>{{ post.title }}</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        {{ post.text | truncate(255) | safe }}
                        <!-- Set the link for read more -->
                        <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-lg-3">
            <div class="row">
                <h5>Recent Posts</h5>
                <ul>
                    {% for post in recent %}
                        <!-- Set the link for recent posts. -->
                        <li><a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="row">
                <h5>Popular Tags</h5>
                <ul>
                    {% for tag in top_tags %}
                        <li><a href="{{ url_for('blog.tag', tag_name=tag[0].name) }}">{{ tag[0].name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- Call the Macro: `render_pagination` from base.html -->
        {{ render_pagination(posts, 'blog.home') }}
    </div>
{% endblock %}

app/templates/blog/new_post.html
{% extends "base.html" %}

{% block title %}New Post{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Create A New Post</h1>
  <form method="POST" action="{{ url_for('blog.new_post') }}">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label }}
      {% if form.title.errors %}
        {% for e in form.title.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.title(class_='form-control') }}
    </div>
    <div class="form-gruop">
      {{ form.text.label }}
      {% if form.text.errors %}
        {% for e in form.text.errors %}
          <p class="help-block">{{ e }}</p>
        {% endfor %}
      {% endif %}
      {{ form.text(id="editor", class_='form-contril') }}
    </div>
    <input class="btn-primary" type="submit" value="Submit">
  </form>
</div>
{% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

app/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
    <h3>{{ post.title }}</h3>

    <div class="row">
        <div class="col-lg-6">
            <p>Written By <a
                    href="{{ url_for('blog.user', username=post.users.username) }}">{{ post.users.username }}</a>
                on {{ post.publish_date }}</p>
            <p>{{ post.text | safe }}</p>
        </div>
        <div class="column">
            <div class="col-lg-2">
                <a href="{{ url_for('blog.new_post') }}" class="btn btn-primary">New</a>
            </div>
        </div>
        <div class="column">
            <div class="col-lg-2">
                <a href="{{ url_for('blog.edit_post', id=post.id) }}" class="btn btn-primary">Edit</a>
            </div>
        </div>
        <div class="col-lg-12">

            {{ post.publish_date }}:
            {{ post.text }}

            <div class="col-lg-12">
                <h3>New Comment:</h3>
                <!-- Set the form -->
                <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
                    {{ form.hidden_tag() }}
                    <div>
                        <!-- Field: `name` label -->
                        {{ form.name.label }}
                        {% if form.name.errors %}
                            {% for e in form.name.errors %}
                                <p class="help-block">{{ e }}</p>
                            {% endfor %}
                        {% endif %}
                        {{ form.name(class_="form-control") }}
                    </div>
                    <div class="form-group">
                        {{ form.text.label }}
                        {% if form.text.errors %}
                            {% for e in form.text.errors %}
                                <p class="help-block">{{ e }}</p>
                            {% endfor %}
                        {% endif %}
                        {{ form.text(class_='form-control') }}
                    </div>
                    <input class="btn btn-primary" type="submit" value="Add Comment">
                </form>
            </div>
{% endblock %}